### PR TITLE
Add SHA-256 as a possible algorithm for digest authentication

### PR DESCRIPTION
**Pull request by AndreasHuber-CH**
Similar to MD5 & SHA1 that are already present.

### CODE REVIEW

**Comment by taurus-forever** [comment]
Hi,

This is a great improvement!
Please sent them upstream https://github.com/nils-ohlmeier/sipsak :-)

**Comment by AndreasHuber-CH** [comment]
Hi,

Sorry, I'm new to github... But do you want me to create another pull request for https://github.com/nils-ohlmeier/sipsak instead of https://github.com/sipsak/sipsak.
And how do I do that? Should I add https://github.com/nils-ohlmeier/sipsak as another remote? Or should I have forked https://github.com/nils-ohlmeier/sipsak in the first place? (I just found out that the master of https://github.com/sipsak/sipsak does cannot be built on my machine because the configure script gives a bunch of errors while https://github.com/nils-ohlmeier/sipsak builds just fine.)

Thanks
Andreas

**Comment by taurus-forever** [comment]
> But do you want me to create another pull request for https://github.com/nils-ohlmeier/sipsak instead of https://github.com/sipsak/sipsak?

Yes, current one is sipwise/sipsak, not a sipsak/sipsak :-)

Sipwise published our locally modified version of sipsak on github before Nils migrated sipsak to github. And currently we are trying to push our local fixes/changes to upstream 'nils-ohlmeier/sipsak'.
Which is hard as Nils doesn't have a time to support/improve sipsak.
Still it replies on ping in Linkedin to submit some pull requests :-)

So, yes, you should create a new pull request to https://github.com/nils-ohlmeier/sipsak

> And how do I do that? Should I add https://github.com/nils-ohlmeier/sipsak as another remote? Or should I have forked https://github.com/nils-ohlmeier/sipsak in the first place? (I just found out that the master of https://github.com/sipsak/sipsak does cannot be built on my machine because the configure script gives a bunch of errors while https://github.com/nils-ohlmeier/sipsak builds just fine.)

No, you cannot do it via remote repo, as this is two completely different repositories, I recommend you make a patch from your make a 6 patches for your changes, clone Nils repository and apply them there -> create a pull request. 

I would really like to see your changes as a part of Nils sipsak tool!

**Comment by AndreasHuber-CH** [comment]
Ok, I'll do that.

**Pull request closed without merging**
